export type Page =
  | 'overview'
  | 'clients'
  | 'operations'
  | 'analytics'
  | 'loyalty'
  | 'wheel'
  | 'achievements'
  | 'shop'
  | 'promotions'
  | 'broadcast'
  | 'brand'
  | 'settings'
  | 'audit'
  | 'platform'
  | 'companies'
  | 'venues'
  | 'developer'
