
const fs=require('fs'),path=require('path'),assert=require('assert/strict')
function walk(d){return fs.existsSync(d)?fs.readdirSync(d).flatMap(n=>{const f=path.join(d,n),s=fs.statSync(f);return s.isDirectory()?walk(f):[f]}):[]}
const runtime=[...walk('server'),...walk('src')].filter(f=>/\.(ts|tsx)$/.test(f)&&!f.includes('/tests/'))
const source=runtime.map(f=>fs.readFileSync(f,'utf8')).join('\n')
const migrations=walk('admin-migrations').map(f=>fs.readFileSync(f,'utf8')).join('\n')
const demo=fs.readFileSync('src/phaseC/DemoMode.tsx','utf8')
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))

assert.equal(pkg.scripts.start,'node dist-server/index.js')
assert.ok(!source.includes('process.env.DATABASE_URL'))
assert.ok(!source.includes('PIVNIK_INTERNAL_PORT'))
assert.ok(!source.includes('spawn(process.execPath'))
assert.ok(!source.match(/\b(?:import|require)\b[^\n]*(?:universal-server|server\.js|vk-platform|account-link)/))
assert.ok(!migrations.match(/\bDROP\s+(?:TABLE|COLUMN)\b/i))
assert.ok(!migrations.match(/\bTRUNCATE\b/i))
assert.ok(!migrations.match(/\bALTER\s+TABLE\s+(?:users|wallets|transactions|bars|bar_customers|user_identities)\b/i))
assert.ok(!migrations.match(/\bDELETE\s+FROM\s+(?:users|wallets|transactions|bars|bar_customers|user_identities)\b/i))
assert.ok(!demo.includes('apiPost('))
assert.ok(!demo.includes('apiPut('))
assert.ok(!demo.includes('/api/admin/'))
const router=fs.readFileSync('server/router.ts','utf8'),index=fs.readFileSync('server/index.ts','utf8')
assert.ok(router.includes("url.pathname.startsWith('/api/admin/')"))
assert.ok(index.includes("url.pathname.startsWith('/api/')"))
assert.ok(index.includes('NON_ADMIN_API_REJECTED'))
console.log('isolation-check: PASS')
console.log(`admin runtime files=${runtime.length}`)
console.log('customer runtime imports=0')
console.log('destructive legacy migrations=0')
console.log('Demo Mode production API writes=0')
console.log('Admin service customer API namespace=0')
