declare module 'lucide-react' {
 export const Activity: any
 export const AlertTriangle: any
 export const ArrowUpRight: any
 export const BarChart3: any
 export const Bell: any
 export const Building2: any
 export const CalendarDays: any
 export const Check: any
 export const ChevronDown: any
 export const ChevronLeft: any
 export const ChevronRight: any
 export const CircleDollarSign: any
 export const CircleHelp: any
 export const ClipboardList: any
 export const Coins: any
 export const Crown: any
 export const Database: any
 export const FileText: any
 export const Filter: any
 export const Gift: any
 export const GripVertical: any
 export const LayoutDashboard: any
 export const LoaderCircle: any
 export const LockKeyhole: any
 export const LogOut: any
 export const Menu: any
 export const MoreHorizontal: any
 export const Palette: any
 export const Pencil: any
 export const Plus: any
 export const RefreshCcw: any
 export const RefreshCw: any
 export const Save: any
 export const Search: any
 export const Settings: any
 export const ShieldCheck: any
 export const ShoppingBag: any
 export const SlidersHorizontal: any
 export const Sparkles: any
 export const Store: any
 export const Target: any
 export const TicketPercent: any
 export const TrendingDown: any
 export const TrendingUp: any
 export const Trophy: any
 export const UserRound: any
 export const Users: any
 export const WalletCards: any
 export const X: any
 export const Zap: any
}
